export const CREATE_EVENT_REQUEST = "CREATE_EVENT_REQUEST";
export const CREATE_EVENT_SUCCESS = "CREATE_EVENT_SUCCESS";
export const CREATE_EVENT_ERROR = "CREATE_EVENT_ERROR";

export const FETCH_ALL_EVENTS_REQUEST = "FETCH_ALL_EVENTS_REQUEST";
export const FETCH_ALL_EVENTS_SUCCESS = "FETCH_ALL_EVENTS_SUCCESS";
export const FETCH_ALL_EVENTS_ERROR = "FETCH_ALL_EVENTS_ERROR";

export const FETCH_MODULES_REQUEST = "FETCH_MODULES_REQUEST";
export const FETCH_MODULES_SUCCESS = "FETCH_MODULES_SUCCESS";
export const FETCH_MODULES_ERROR = "FETCH_MODULES_ERROR";