export const START_EVENT = "START_EVENT";
export const END_EVENT = "END_EVENT";

export const SOCKET_CONNECTED = "SOCKET_CONNECTED";
export const SOCKET_DISCONNECTED = "SOCKET_DISCONNECTED";

export const TIMER_SYNC = "TIMER_SYNC";
export const TIMER_OVER = "TIMER_OVER";

export const CONTENTFUL_EVENT_DATA = "CONTENTFUL_EVENT_DATA";

export const EVENT_DATA_SUBMIT_SUCCESSFUL = "EVENT_DATA_SUBMIT_SUCCESSFUL";
export const EVENT_DATA_SUBMIT_ERROR = "EVENT_DATA_SUBMIT_ERROR";
